[package]
name = "reddit_api_impl"
version = "0.1.0"
authors = ["Mayowa Aj <sagaraaj69@gmail.com>"]
edition = "2018"


[dependencies]
rocket = "0.4.4"
diesel = { version = "1.0.0", features = ["mysql"] }
dotenv = "0.15.0"